name: ESP-IDF CI Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Importante si usas componentes externos

      - name: build esp-idf project
        uses: espressif/shared-github-actions/build_apps@v3
        with:
          path: '.'
          target: 'esp32' # Puedes cambiarlo a esp32s3, esp32c3, etc.
          # Por defecto usa la última versión estable, pero puedes fijar una:
          # esp_idf_version: 'v5.2.1'
