name: ESP-IDF ESP32 Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: espressif/idf:release-v5.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Initialize and Build Project
        run: |
          # Activamos el entorno de ESP-IDF usando su entrypoint oficial
          . /opt/esp/entrypoint.sh
          
          # Ahora idf.py está disponible en el PATH
          idf.py set-target esp32
          idf.py build
