name: espressif/idf:release-v5.2

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    
    container:
      image: espressif/idf:release-v5.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Initialize and Build Project
        run: |
          # Activamos el entorno de ESP-IDF usando su entrypoint oficial
          . /opt/esp/entrypoint.sh
          cp -r $IDF_PATH/examples/get-started/hello_world .
          
          # Ahora idf.py está disponible en el PATH
          #cd hello_world
          #idf.py set-target esp32
          #idf.py build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-hello-world-example
          path: |
            hello_world
          retention-days: 2
